using System;
using System.Windows.Forms;

namespace Event_Ticket_Handling
{
    // This is the main form of the application (currently called Form1).
    // From here, the user can choose whether to log in as Admin or Attendee.
    public partial class Form1 : Form
    {
        // Constructor: this method is called when the form is first created.
        // It sets up all the controls (buttons, labels, etc.) on the form.
        public Form1()
        {
            InitializeComponent(); // Automatically generated by Visual Studio
        }

        // This method runs when the "Admin" button is clicked.
        private void button1_Click(object sender, EventArgs e)
        {
            this.Hide(); // Hide the current form (Form1)

            // Create a new Admin_Login form object
            Admin_Login adminLogin = new Admin_Login();

            // Show the Admin login form
            adminLogin.Show();
        }

        // This method runs when the "Attendee" button is clicked.
        private void button2_Click(object sender, EventArgs e)
        {
            this.Hide(); // Hide the current form (Form1)

            // Create a new Attendee_Login form object
            Attendee_Login attendeeLogin = new Attendee_Login();

            // Show the Attendee login form
            attendeeLogin.Show();
        }

        // This method runs if the picture box is clicked.
        // Currently empty — you can add code here if you want an action to happen when the image is clicked.
        private void pictureBox1_Click(object sender, EventArgs e)
        {
        }

        // This method runs when the form first loads.
        // Right now it does nothing, but you can add setup code here if needed.
        private void Form1_Load(object sender, EventArgs e)
        {
        }

        // This method runs when the label is clicked.
        // Currently does nothing — you could add functionality if required.
        private void label1_Click(object sender, EventArgs e)
        {
        }
    }
}
